---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tapntrac/public_html/devapi.tapntrack.in/
    - rsync -av --exclude 'tenants_data' ./ $DEPLOYPATH
    - cd $DEPLOYPATH
    - if [ ! -f composer.phar ]; then curl -sS https://getcomposer.org/installer | php; fi
    - php composer.phar install --optimize-autoloader --no-dev
    - php composer.phar dump-autoload --optimize
    - php artisan passport:keys
    - php artisan route:cache
    - php artisan view:cache
    - chmod -R 755 storage
    - chmod -R 755 bootstrap/cache