---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tapntrac/public_html/devapi.tapntrack.in/
    - /bin/cp -R public/* $DEPLOYPATH
    - cd /home/tapntrac/public_html/devapi.tapntrack.in
    - if [ ! -f composer.phar ]; then curl -sS https://getcomposer.org/installer | php; fi
    - php composer.phar install --optimize-autoloader --no-dev
    - php composer.phar dump-autoload --optimize
    - php artisan passport:keys
    - php artisan route:cache
    - php artisan view:cache
    - chmod -R 777 storage
    - chmod -R 777 bootstrap/cache
