---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tapntrac/public_html/devapi.tapntrack.in/
    - echo "Deploying to $DEPLOYPATH"
    - find . -path ./tenants_data -prune -o -print0 | xargs -0 -I {} cp -r {} $DEPLOYPATH
    - echo "Files copied to $DEPLOYPATH"
    - cd $DEPLOYPATH
    - if [ ! -f composer.phar ]; then echo "Installing Composer"; curl -sS https://getcomposer.org/installer | php; fi
    - echo "Running Composer install"
    - php composer.phar install --optimize-autoloader --no-dev
    - echo "Dumping autoload"
    - php composer.phar dump-autoload --optimize
    - echo "Running Artisan commands"
    - php artisan passport:keys
    - php artisan route:cache
    - php artisan view:cache
    - chmod -R 755 storage
    - chmod -R 755 bootstrap/cache
    - echo "Deployment completed"
